### ISSUE TITLE
Implementation in MWAA Issue

### ISSUE THREAD

**Issue by nsoria1** [tomasfarias/airflow-dbt-python#1]
Hi Tomas, thank you very much for posting this solution.

I have been trying to implement this in an MWAA Airflow instance without luck. Here is a sample of the log that I am getting.

`AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_dbt_operator
AIRFLOW_CTX_TASK_ID=dbt_test
AIRFLOW_CTX_EXECUTION_DATE=2021-06-01T20:56:36.080170+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-01T20:56:36.080170+00:00
[2021-06-01 20:56:40,658] {{taskinstance.py:1482}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/operators/dbt.py", line 68, in execute
    args.extend(self.args_list())
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/operators/dbt.py", line 79, in args_list
    value = getattr(self, arg)
AttributeError: project_dir`

- Airflow instance is the latest provided by AWS
- It has been tested locally using the docker image provided by AWS
- Code has been copied and pasted to DAG from the example posted.

**Comment by tomasfarias** [comment]
Hey @nsoria1, sorry for the late reply, it's just me working on this, and my full-time job has been very taxing. Hope you understand.

`airflow-dbt-python` has been bumped up quite a few versions since you attempted to use it, maybe you caught it at a more early, buggy, state? Would be great to know if you are still having any issues with the latest version. I have been using `airflow-dbt-python` very successfully with MWAA, so I can provide some pointers if you need them.

**Comment by tomasfarias** [comment]
Since we didn't get any updates, I'll be closing this issue for now. Feel free to reopen if anything comes up.
