### ISSUE TITLE
Can't remove directory of log after dbt run

### ISSUE THREAD

**Issue by lifnaja** [tomasfarias/airflow-dbt-python#106]
Hi, we try to upgrade airflow-dbt-python 1.0.2 from version 0.14.5

But after we upgraded we got the error can't remove log directory 

```
[2023-03-27, 04:47:29 UTC] {functions.py:222} INFO - [0m04:47:29  Done. PASS=16 WARN=0 ERROR=0 SKIP=0 TOTAL=16
[2023-03-27, 04:47:32 UTC] {dbt.py:176} ERROR - An error has ocurred while executing dbt run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/operators/dbt.py", line 170, in execute
    result = self.dbt_hook.run_dbt_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 207, in run_dbt_task
    with self.dbt_directory(
  File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 296, in dbt_directory
    with TemporaryDirectory(prefix="airflow_tmp") as tmp_dir:
  File "/usr/local/lib/python3.10/tempfile.py", line 869, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.10/tempfile.py", line 873, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "/usr/local/lib/python3.10/tempfile.py", line 855, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/local/lib/python3.10/shutil.py", line 724, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.10/shutil.py", line 663, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 661, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'logs'
```

Our code.
```
dbt_run = DbtRunOperator(
        task_id="dbt_run",
        project_dir=s3://{S3_BUCKET}/dbt/dbt-project.zip,
        profiles_dir=s3://{S3_BUCKET}/dbt/profiles.yml,
        project_conn_id=S3_CONN,
        profiles_conn_id=S3_CONN,
        fail_fast=True,
    )
```
We  run on airflow version 2.5.0 with python  3.10.8

**Comment by tomasfarias** [comment]
Hey, thanks for reporting an issue.

This is definitely a weird one.

Using a `TemporaryDirectory` context manager should handle temporary directory cleanup; the fact that `logs/` is empty or not shouldn't impact cleanup as it should be deleted anyways. I've researched online and this could be caused by a thread or other process keeping a file handle open and stopping Python from deleting it. This could even be a bug in Python...

Which dbt-core version are you using?

For the time being, I'll ignore errors in cleanup. This could cause some space leak though.
