### ISSUE TITLE
ModuleNotFoundError: No module named 'dulwich'

### ISSUE THREAD

**Issue by KarthikRajashekaran** [tomasfarias/airflow-dbt-python#112]
I am trying to use gitlab dbt project repo using dbt remote 
```
 dbt_run = DbtRunOperator(
        task_id="dbt_run",
        project_dir="https://domain/abc/-/tree/main/dbt/db_metrics?private_token=abcdesf",
        dbt_conn_id="dbt_conn_id",
        target="dev",
        do_xcom_push_artifacts=["run_results.json"],
    )

```
```
[2023-03-30, 03:09:38 UTC] {dbt.py:176} ERROR - An error has ocurred while executing dbt run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 148, in get_remote
    return self.remotes[(scheme, conn_id)]
KeyError: ('https', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 322, in dbt_directory
    project_dir, profiles_dir = self.prepare_directory(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 367, in prepare_directory
    project_dir_path = self.download_dbt_project(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 180, in download_dbt_project
    remote = self.get_remote(scheme, self.project_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 150, in get_remote
    remote = get_remote(scheme, conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/remote.py", line 152, in get_remote
    from .git import DbtGitRemoteHook
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/git.py", line 6, in <module>
    from dulwich.client import HttpGitClient, SSHGitClient, TCPGitClient
ModuleNotFoundError: No module named 'dulwich'

```

**Comment by KarthikRajashekaran** [comment]
Tentative release for v1.0.4 ?

**Comment by tomasfarias** [comment]
v1.0.4 going out later today assuming CI is green.

**Comment by alvaromendoza** [comment]
I see that [v1.0.4](https://pypi.org/project/airflow-dbt-python/1.0.4/) is already available on PyPI. However, doing `pip install airflow-dbt-python==1.0.4` seems to install a version of the code that does not have the changes from [#113](https://github.com/tomasfarias/airflow-dbt-python/pull/113). Also, `pyproject.toml` still says `version = "1.0.3"`. Is there a problem? Or am I missing something?

**Comment by tomasfarias** [comment]
Thanks for bringing this up @alvaromendoza.

I think I may have tagged the wrong commit, and thus 1.0.4 was deployed without the changes. Unfortunately, PyPI doesn't allow overwriting existing releases, so I will go ahead and do a 1.0.5 release.

Sorry for the inconveniences. The deployment pipeline is all automated except for bumping the version and tagging the commit, and I couldn't get that right :sweat_smile:

**Comment by tomasfarias** [comment]
Just pushed tag v1.0.5 which does have the latest changes as you can verify looking at the tree: https://github.com/tomasfarias/airflow-dbt-python/tree/v1.0.5/airflow_dbt_python/hooks.

It should be deployed shortly to PyPI.

**Comment by FouadApp** [comment]
Preferably to add  verify ssl = bool

 to avoid this error:
SSL: CERTIFICATE_VERIFY_FAILED

**Comment by KarthikRajashekaran** [comment]
does version v1.0.5 support both remote GitLab clone and airflow connections?
