### ISSUE TITLE
DbtProjectError(NO_SUPPLIED_PROFILE_ERROR) when using Airflow Connection as target

### ISSUE THREAD

**Issue by ryelko** [tomasfarias/airflow-dbt-python#124]
We have a very simple DAG that uses S3 as the project_dir and an airflow connection for the target.

We're using Airflow 2.0.2 via MWAA, dbt-core 1.2.6, and airflow-dbt-python 1.0.5. 

However we get the following error:

```python
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/operators/dbt.py", line 173, in execute
    **vars(self),
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 239, in run_dbt_task
    task, runtime_config = config.create_dbt_task(extra_target)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/utils/configs.py", line 245, in create_dbt_task
    runtime_config = self.create_runtime_config(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/utils/configs.py", line 270, in create_runtime_config
    project, profile = self.create_dbt_project_and_profile(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/utils/configs.py", line 292, in create_dbt_project_and_profile
    profile = self.create_dbt_profile(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/utils/configs.py", line 364, in create_dbt_profile
    profile = raw_profiles.setdefault(self.profile_name, {})
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/utils/configs.py", line 318, in profile_name
    profile_name = Profile.pick_profile_name(self.profile, project_profile_name)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 204, in pick_profile_name
    raise DbtProjectError(NO_SUPPLIED_PROFILE_ERROR)
dbt.exceptions.DbtProjectError: Runtime Error
  dbt cannot run because no profile was specified for this dbt project.
  To specify a profile for this project, add a line like the this to
  your dbt_project.yml file:
  
  profile: [profile name]
  
  Here, [profile name] should be replaced with a profile name
  defined in your profiles.yml file. You can find profiles.yml here:
  
  /usr/local/airflow/.dbt/profiles.yml
  ```
  
  We are following the examples provided so I'm not sure what we can do to fix this so any help would be appreciated.

**Comment by ryelko** [comment]
I took not needing the `profiles.yml` file to also include not needing the `profile` configuration in `dbt_project.yml`. Adding some configuration there seemed to work fine for now, even though there is no `profiles.yml` that the name relates to anywhere.
