### ISSUE TITLE
DbtLsOperator Error - object has no attribute 'resource_type'.

### ISSUE THREAD

**Issue by nickmala** [tomasfarias/airflow-dbt-python#128]
Hi im trying to run the DbtLsOperator to list out the tables in our 'gold' layer of our transformations and am getting the following error:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 562, in _do_render_template_fields
    value = getattr(parent, attr_name)
AttributeError: 'DbtLsOperator' object has no attribute 'resource_type'. Did you mean: 'resource_types'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 564, in _do_render_template_fields
    raise AttributeError(
AttributeError: 'resource_type' is configured as a template field but DbtLsOperator does not have this attribute.

I have defined my task as :
    get_gold_layer_tables = DbtListOperator(
        task_id="get_gold_layer_tables",
        project_dir=PROJECT_DIR,
    )

So I havent even defined 'resource_type' but I noticed it was defined in the source code:

https://airflow-dbt-python.readthedocs.io/en/latest/_modules/airflow_dbt_python/operators/dbt.html#DbtLsOperator

class DbtLsOperator(DbtBaseOperator):
    """Executes a dbt list (or ls) command.

    The documentation for the dbt command can be found here:
    https://docs.getdbt.com/reference/commands/list.
    """

    template_fields = (
        base_template_fields + selection_template_fields + ["resource_type"]
    )

Not sure if it is that or I am doing something wrong! Cheers

**Comment by tomasfarias** [comment]
Looking at the config, this parameter should be `resource_types`.

Strange that it wasn't caught by the tests, can I ask which versions of Python, Airflow, dbt, and airflow-dbt-python are you running?

In the meantime, I can see if I can reproduce the error. As a workaround, have you tried setting `resource_types`? E.g. `DbtLsOperator(resource_types=["all"])`

**Comment by tomasfarias** [comment]
I am not able to reproduce with:
```
    op = DbtLsOperator(
        task_id="dbt_task",
        project_dir=dbt_project_file.parent,
        profiles_dir=profiles_file.parent,
        do_xcom_push=True,
    )
```

This seems to work just fine. Happy to update `resource_type` to `resource_types` if tests pass though just in case that's the issue.
