### ISSUE TITLE
s3_conn_id is not recornized

### ISSUE THREAD

**Issue by Alex-Ivanov777** [tomasfarias/airflow-dbt-python#140]
Broken DAG ([dags/run_dbt_projects5.py]
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 788, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DbtRunOperator (task_id: run_dbt). Invalid arguments were:
**kwargs: {'s3_conn_id': 's3_dbt'}

**Comment by millin** [comment]
This is a documentation problem. 
I think you need the `project_conn_id` attribute instead.
