### ISSUE TITLE
No dbt_project.yml found when using S3 backend in MWAA

### ISSUE THREAD

**Issue by validumitru** [tomasfarias/airflow-dbt-python#71]
We are trying to setup airflow-dbt-python in MWAA (airflow 2.2.2) and getting: no dbt_project.yml found when the yml file is definitely in the s3 bucket.

Our dag, as an example: 

`
from datetime import datetime, timedelta
from airflow.utils.dates import days_ago

from airflow import DAG

from airflow_dbt_python.operators.dbt import DbtDocsGenerateOperator

with DAG(
    dag_id="dbt_docs",
    schedule_interval="@daily",
    start_date=days_ago(1),
    catchup=False,
    dagrun_timeout=timedelta(minutes=60),
) as dag:

    dbt_docs = DbtDocsGenerateOperator(
        task_id="dbt_docs",
        project_dir="s3://xxx-bi-dbt/",
        profiles_dir="s3://xxx-bi-dbt/profiles/",
        profile="xxx"
    )

    dbt_docs
`

The airflow logs: 

`
[2022-07-03, 08:06:05 UTC] {{dbt.py:271}} INFO - Initializing temporary directory: /tmp/airflowtmppgtpg7w3
[2022-07-03, 08:06:05 UTC] {{base.py:43}} INFO - Pulling dbt profiles file from: s3://xxx-bi-dbt/profiles/
[2022-07-03, 08:06:05 UTC] {{base_aws.py:401}} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-07-03, 08:06:05 UTC] {{base_aws.py:190}} INFO - No credentials retrieved from Connection
[2022-07-03, 08:06:05 UTC] {{base_aws.py:93}} INFO - Creating session with aws_access_key_id=None region_name=None
[2022-07-03, 08:06:05 UTC] {{base_aws.py:168}} INFO - role_arn is None
[2022-07-03, 08:06:05 UTC] {{s3.py:202}} INFO - Downloading S3Object s3.Object(bucket_name='xxx-bi-dbt', key='profiles/profiles.yml') to: /tmp/airflowtmppgtpg7w3/profiles.yml
[2022-07-03, 08:06:05 UTC] {{base.py:67}} INFO - Pulling dbt project files from: s3://xxx-bi-dbt/
[2022-07-03, 08:06:05 UTC] {{base_aws.py:401}} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-07-03, 08:06:05 UTC] {{base_aws.py:190}} INFO - No credentials retrieved from Connection
[2022-07-03, 08:06:05 UTC] {{base_aws.py:93}} INFO - Creating session with aws_access_key_id=None region_name=None
[2022-07-03, 08:06:05 UTC] {{base_aws.py:168}} INFO - role_arn is None
[2022-07-03, 08:06:05 UTC] {{dbt.py:177}} INFO - Running dbt configuration: GenerateTaskConfig(cls=<class 'dbt.task.generate.GenerateTask'>, project_dir='/tmp/airflowtmppgtpg7w3/', profiles_dir='/tmp/airflowtmppgtpg7w3/', profile='xxx', target=None, compiled_target=None, cache_selected_only=None, fail_fast=None, single_threaded=None, threads=None, use_experimental_parser=None, vars='{}\n', warn_error=None, log_format=None, log_cache_events=False, record_timing_info=None, debug=None, quiet=None, no_print=None, defer=None, partial_parse=False, use_colors=None, static_parser=None, version_check=None, send_anonymous_usage_stats=None, write_json=None, exclude=None, select=None, selector_name=None, state=None, models=None, compile=True, which='generate')
[2022-07-03, 08:06:05 UTC] {{dbt.py:182}} ERROR - There was an error executing dbt
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/operators/dbt.py", line 180, in execute
    success, results = self.dbt_hook.run_dbt_task(config)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 744, in run_dbt_task
    task, runtime_config = config.create_dbt_task(extra_target)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 279, in create_dbt_task
    runtime_config = self.create_runtime_config(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 307, in create_runtime_config
    project, profile = self.create_dbt_project_and_profile(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 329, in create_dbt_project_and_profile
    profile = self.create_dbt_profile(extra_targets)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 408, in create_dbt_profile
    self.profile_name, {}
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 350, in profile_name
    project_profile_name = self.partial_project.render_profile_name(
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_dbt_python/hooks/dbt.py", line 376, in partial_project
    project_root, verify_version=version_check
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dbt/config/project.py", line 634, in partial_load
    verify_version=verify_version,
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dbt/config/project.py", line 475, in from_project_root
    project_dict = _raw_project_from(project_root)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/dbt/config/project.py", line 160, in _raw_project_from
    "no dbt_project.yml found at expected path {}".format(project_yaml_filepath)
dbt.exceptions.DbtProjectError: Runtime Error
  no dbt_project.yml found at expected path /tmp/airflowtmppgtpg7w3/dbt_project.yml
`

Could you give us a hint here ?

**Comment by validumitru** [comment]
Turns out the issue is having the project files in the root of the s3 bucket. Moving it in a subfolder fixed it :)
